<?php
/**
 * freeSIEM dial-home for AJNanda (theme) — generated by freeSIEM Core.
 *
 * Usage (call boot() at the top level of the main file, not inside a hook, so the
 * activation hook registers):
 *   Plugin: require_once __DIR__ . '/<path>/freesiem-dial-home-ajnanda.php';
 *           Freesiem_Dial_Home_ajnanda::boot(__FILE__);
 *   Theme:  require_once get_template_directory() . '/<path>/freesiem-dial-home-ajnanda.php';
 *           Freesiem_Dial_Home_ajnanda::boot(get_template_directory() . '/style.css');
 *
 * Reports to freeSIEM Core on activation / theme switch, when the version changes,
 * when WordPress / PHP / the active theme / the site URL change, and every 12 hours. Any request can trigger it (no login needed); it is sent
 * after the response has gone out, so visitors never wait on Core, and a failed
 * send is retried after 10 minutes. *.ddev.site sites report to the local Core.
 *
 * Sends: site URL/name, WP/PHP/DB versions, locale, timezone, active theme name,
 * environment, and a SHA-256 of the admin email. Nothing else. Turn it off with
 *   add_filter('freesiem_dial_home_enabled', '__return_false');
 */
if (!defined('ABSPATH')) {
	exit;
}

if (!class_exists('Freesiem_Dial_Home_ajnanda')) {
	final class Freesiem_Dial_Home_ajnanda
	{
		const SLUG = 'ajnanda';
		const NAME = 'AJNanda';
		const TYPE = 'theme';
		const SECRET = 'FwqHd2lNQaG_tpNXQL2O-v9vnSVZx1T0JQOlMmFJ008';
		const PROD_ENDPOINT = 'https://core.freesiem.com/api/v1/install-base/dial-home';
		const LOCAL_ENDPOINT = 'https://host.docker.internal:8443/api/v1/install-base/dial-home';
		const HEARTBEAT_EVERY = 43200; // 12 hours
		const RETRY_AFTER = 600;       // 10 minutes after any attempt

		private static $file = '';
		private static $queued = false;

		public static function boot($file)
		{
			self::$file = (string) $file;

			if (self::TYPE === 'theme') {
				add_action('after_switch_theme', function () {
					Freesiem_Dial_Home_ajnanda::send('activation');
				});
			} else {
				register_activation_hook(self::$file, function () {
					Freesiem_Dial_Home_ajnanda::send('activation');
				});
			}

			add_action('init', function () {
				Freesiem_Dial_Home_ajnanda::maybe_queue();
			}, 20);
		}

		public static function maybe_queue()
		{
			if (self::$queued || !apply_filters('freesiem_dial_home_enabled', true, self::SLUG)) {
				return;
			}

			$version = self::version();
			$upgrade_due = $version !== '' && $version !== (string) get_option(self::option('version'), '');
			$heartbeat_due = (time() - (int) get_option(self::option('last_heartbeat'), 0)) >= self::HEARTBEAT_EVERY;
			// WordPress / PHP / theme / URL changed since Core was last told.
			$changed = self::fingerprint() !== (string) get_option(self::option('fingerprint'), '');

			if (!$upgrade_due && !$heartbeat_due && !$changed) {
				return;
			}
			if ((time() - (int) get_option(self::option('last_attempt'), 0)) < self::RETRY_AFTER) {
				return;
			}

			self::$queued = true;
			$event = $upgrade_due ? 'upgrade' : ($changed ? 'change' : 'heartbeat');

			add_action('shutdown', function () use ($event) {
				if (function_exists('fastcgi_finish_request')) {
					fastcgi_finish_request();
				}
				Freesiem_Dial_Home_ajnanda::send($event);
			});
		}

		// Last attempt: array('ok', 'event', 'at', 'status_code', 'message'), or empty.
		public static function last_result()
		{
			return (array) get_option(self::option('last_result'), array());
		}

		// Hash of the facts Core displays; a difference means Core's copy is out of date.
		private static function fingerprint()
		{
			return hash('sha256', (string) wp_json_encode(array(
				get_bloginfo('version'),
				PHP_VERSION,
				(string) wp_get_theme()->get('Name'),
				site_url(),
				home_url(),
				self::version(),
				function_exists('wp_get_environment_type') ? wp_get_environment_type() : 'production',
			)));
		}

		private static function version()
		{
			if (self::TYPE === 'theme') {
				return (string) wp_get_theme(basename(dirname(self::$file)))->get('Version');
			}
			$data = get_file_data(self::$file, array('Version' => 'Version'));

			return (string) (isset($data['Version']) ? $data['Version'] : '');
		}

		private static function option($suffix)
		{
			return 'freesiem_dial_home_' . str_replace('-', '_', self::SLUG) . '_' . $suffix;
		}

		private static function is_local()
		{
			$host = strtolower((string) wp_parse_url(home_url(), PHP_URL_HOST));

			return substr($host, -10) === '.ddev.site';
		}

		private static function endpoint()
		{
			$endpoint = self::is_local() ? self::LOCAL_ENDPOINT : self::PROD_ENDPOINT;

			return (string) apply_filters('freesiem_dial_home_endpoint', $endpoint, self::SLUG);
		}

		private static function install_uuid()
		{
			$uuid = (string) get_option(self::option('uuid'), '');
			if ($uuid === '') {
				$uuid = wp_generate_uuid4();
				add_option(self::option('uuid'), $uuid, '', false);
			}

			return $uuid;
		}

		public static function payload($event)
		{
			global $wpdb;

			$home = home_url();
			$email = strtolower(trim((string) get_option('admin_email', '')));
			$version = self::version();

			return array(
				'addon_name' => self::NAME,
				'addon_slug' => self::SLUG,
				'addon_type' => self::TYPE === 'theme' ? 'wordpress-theme' : 'wordpress-plugin',
				'addon_version' => $version !== '' ? $version : '0',
				'install_uuid' => self::install_uuid(),
				'site_url' => site_url(),
				'home_url' => $home,
				'site_host' => (string) wp_parse_url($home, PHP_URL_HOST),
				'site_name' => (string) get_bloginfo('name'),
				'wp_version' => (string) get_bloginfo('version'),
				'php_version' => PHP_VERSION,
				'db_version' => isset($wpdb) ? (string) $wpdb->db_version() : '',
				'multisite' => is_multisite(),
				'locale' => (string) get_locale(),
				'timezone' => (string) wp_timezone_string(),
				'theme' => (string) wp_get_theme()->get('Name'),
				'environment' => function_exists('wp_get_environment_type') ? wp_get_environment_type() : 'production',
				'admin_email_hash' => 'sha256:' . hash('sha256', $email),
				'connected_to_core' => (bool) apply_filters('freesiem_dial_home_connected', false, self::SLUG),
				'event' => sanitize_key($event),
				'sent_at' => gmdate('c'),
				'meta' => array(
					'source' => self::TYPE === 'theme' ? 'wordpress-theme' : 'wordpress-plugin',
					'channel' => self::is_local() ? 'local-dev' : 'production',
				),
			);
		}

		public static function send($event)
		{
			if (!apply_filters('freesiem_dial_home_enabled', true, self::SLUG)) {
				return null;
			}

			update_option(self::option('last_attempt'), time(), false);

			$body = wp_json_encode(self::payload($event), JSON_UNESCAPED_SLASHES);
			if (!is_string($body)) {
				return null;
			}
			$timestamp = (string) time();
			$signature = hash_hmac('sha256', self::SLUG . "\n" . $timestamp . "\n" . $body, self::SECRET);

			$response = wp_remote_post(self::endpoint(), array(
				'timeout' => 8,
				// The local Core is served with a self-signed certificate.
				'sslverify' => !self::is_local(),
				'headers' => array(
					'Content-Type' => 'application/json',
					'X-FS-Addon' => self::SLUG,
					'X-FS-Timestamp' => $timestamp,
					'X-FS-Signature' => $signature,
				),
				'body' => $body,
			));

			$code = is_wp_error($response) ? 0 : (int) wp_remote_retrieve_response_code($response);
			$ok = $code >= 200 && $code < 300;

			update_option(self::option('last_result'), array(
				'ok' => $ok,
				'event' => $event,
				'at' => gmdate('c'),
				'status_code' => $code,
				'message' => is_wp_error($response) ? $response->get_error_message() : '',
			), false);

			if ($ok) {
				// Only a successful report counts as "Core knows this version".
				update_option(self::option('version'), self::version(), false);
				update_option(self::option('last_heartbeat'), time(), false);
				update_option(self::option('fingerprint'), self::fingerprint(), false);
			}

			return $response;
		}
	}
}
