<?php if (! defined('ABSPATH')) { exit; } ?>
<div class="notice notice-info inline"><p><?php esc_html_e('This is behavioral detection, not proof of who sent a request. AJNanda labels high-confidence probe patterns as suspicious and keeps reported crawler identity separate from verified identity. Only requests that reached WordPress can appear here.', 'ajnanda'); ?></p></div>
<?php if (! $suspicious_bots['enabled']) : ?>
<div class="ajnanda-admin-section"><span class="ajnanda-admin-pill is-warning"><?php esc_html_e('Detection disabled', 'ajnanda'); ?></span><h2><?php esc_html_e('Suspicious bot detection is disabled', 'ajnanda'); ?></h2><p><?php esc_html_e('Existing crawler observations are not currently being analyzed for suspicious request patterns.', 'ajnanda'); ?></p><a class="button button-primary" href="<?php echo esc_url(add_query_arg(array('page'=>AJNanda_Search_AI_Admin::PAGE_SLUG,'tab'=>'settings'),admin_url('admin.php'))); ?>"><?php esc_html_e('Configure detection', 'ajnanda'); ?></a></div>
<?php elseif (! AJNanda_Search_AI_Settings::get('search_ai_crawler_logging_enabled')) : ?>
<div class="ajnanda-admin-section"><h2><?php esc_html_e('Crawler logging is disabled', 'ajnanda'); ?></h2><p><?php esc_html_e('Suspicious bot detection analyzes Crawler Log observations. Enable crawler logging to collect eligible requests.', 'ajnanda'); ?></p><a class="button button-primary" href="<?php echo esc_url(add_query_arg(array('page'=>AJNanda_Search_AI_Admin::PAGE_SLUG,'tab'=>'settings'),admin_url('admin.php'))); ?>"><?php esc_html_e('Configure Crawler Logging', 'ajnanda'); ?></a></div>
<?php else : ?>
<div class="ajnanda-readiness-cards ajnanda-crawler-summary">
    <div class="ajnanda-readiness-card"><span><?php esc_html_e('Suspicious requests', 'ajnanda'); ?></span><strong><?php echo esc_html(number_format_i18n($suspicious_bots['total'])); ?></strong></div>
    <div class="ajnanda-readiness-card"><span><?php esc_html_e('Successful sensitive responses', 'ajnanda'); ?></span><strong class="<?php echo $suspicious_bots['successful_sensitive'] ? 'ajnanda-state-fail' : 'ajnanda-state-pass'; ?>"><?php echo esc_html(number_format_i18n($suspicious_bots['successful_sensitive'])); ?></strong></div>
    <div class="ajnanda-readiness-card"><span><?php esc_html_e('Unverified crawler claims', 'ajnanda'); ?></span><strong><?php echo esc_html(number_format_i18n($suspicious_bots['claimed_crawlers'])); ?></strong></div>
    <div class="ajnanda-readiness-card"><span><?php esc_html_e('Period analyzed', 'ajnanda'); ?></span><strong><?php printf(esc_html__('%d days', 'ajnanda'), $suspicious_bots['days']); ?></strong></div>
</div>
<div class="ajnanda-admin-grid ajnanda-overview-main">
<section class="ajnanda-admin-card"><h2><?php esc_html_e('Guidance', 'ajnanda'); ?></h2><ol class="ajnanda-readiness-actions"><?php foreach($suspicious_bots['guidance'] as $item): ?><li><span class="ajnanda-admin-pill is-<?php echo esc_attr($item['state']); ?>"><?php echo esc_html(ucfirst($item['state'])); ?></span><strong><?php echo esc_html($item['title']); ?></strong><p><?php echo esc_html($item['text']); ?></p></li><?php endforeach; ?></ol></section>
<section class="ajnanda-admin-card"><h2><?php esc_html_e('Most-targeted suspicious paths', 'ajnanda'); ?></h2><?php if(!$suspicious_bots['top_paths']): ?><p><?php esc_html_e('No matching paths were observed.', 'ajnanda'); ?></p><?php else:?><ul><?php foreach($suspicious_bots['top_paths'] as $path=>$count): ?><li><code><?php echo esc_html($path); ?></code> <?php echo esc_html(number_format_i18n($count)); ?></li><?php endforeach; ?></ul><?php endif; ?></section>
</div>
<?php if($suspicious_bots['scan_limited']): ?><div class="notice notice-warning inline"><p><?php printf(esc_html__('Analysis was bounded to the newest %d crawler events in this period.', 'ajnanda'), AJNanda_Search_AI_Suspicious_Bot_Detector::MAX_SCAN); ?></p></div><?php endif; ?>
<div class="ajnanda-admin-section"><h2><?php esc_html_e('Recent suspicious requests', 'ajnanda'); ?></h2><table class="widefat striped"><thead><tr><th><?php esc_html_e('Time','ajnanda'); ?></th><th><?php esc_html_e('Reported identity','ajnanda'); ?></th><th><?php esc_html_e('Requested path','ajnanda'); ?></th><th><?php esc_html_e('Result','ajnanda'); ?></th><th><?php esc_html_e('Why flagged','ajnanda'); ?></th></tr></thead><tbody><?php if(!$suspicious_bots['recent']): ?><tr><td colspan="5"><?php esc_html_e('No high-confidence suspicious requests were detected for this period.','ajnanda'); ?></td></tr><?php else: foreach($suspicious_bots['recent'] as $event): ?><tr><td><?php echo esc_html(get_date_from_gmt($event['observed_at'],'M j, Y H:i:s')); ?></td><td><strong><?php echo esc_html($event['reported_identity']); ?></strong><small><?php echo esc_html(str_replace('_',' ',$event['verification_state'])); ?></small></td><td><code><?php echo esc_html($event['request_path']); ?></code></td><td><?php echo esc_html($event['http_status'] ?: '—'); ?> <span class="ajnanda-admin-pill is-<?php echo 'critical'===$event['suspicion']['severity']?'fail':'warning'; ?>"><?php echo esc_html(ucfirst($event['suspicion']['severity'])); ?></span></td><td><?php echo esc_html(implode('; ',array_map(array('AJNanda_Search_AI_Suspicious_Bot_Detector','reason_label'),$event['suspicion']['reasons']))); ?></td></tr><?php endforeach; endif; ?></tbody></table></div>
<?php endif; ?>
